apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ansible-playbook-template
  title: Ansible Playbook!
  description: Launch a Job Template!
  tags:
    - ansible
    - playbook
spec:
  owner: user1
  type: playbook

  parameters:
  - title: Ansible Job Template!
    required:
      - component_id
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
        ui:field: EntityNamePicker
      
  steps:
    - id: launch
      name: Launch
      action: rhaap:launch-job-template
      input:
        token: abc
        values:
          template:
            id: 10
            name: clone-edit-push
    
  output:
    links:
      - title: URL
        url: ${{ steps.launch.output.data.url }}
    text:
      - title: ID
        content: ${{ steps['launch'].output.data.id }}
      - title: Status
        content: ${{ steps['launch'].output.data.status }}
      
