{{- if not (eq .Values.environment "dev") -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
  namespace: "{{ .Values.namespace.name }}"
subjects:
  - kind: ServiceAccount
    name: image-pusher
    namespace: ${{values.component_id}}-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
{{- end }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${{values.user}}-{{ .Values.namespace.name }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ${{values.user}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
