---
- name: Clone, modify config.yaml and push back to Git (with username/password)
  hosts: localhost
  gather_facts: no
  vars:
    git_username: "<>"
    git_password: "<>"
    repo_base_url: "gitlab-gitlab.apps.cluster-b8zs9.b8zs9.sandbox2119.opentlc.com/development/teste.git"
    dest_dir: "/tmp/your_repo"
    file_to_edit: "/tmp/your_repo/config.yaml"
    git_user_name: "Your Name"
    git_user_email: "your_email@example.com"
    commit_message: "Automated update to config.yaml"

  tasks:
    # - name: Build Git repo URL with username and password
    #   set_fact:
    #     repo_url_with_auth: "https://{{ git_username }}:{{ git_password }}@{{ repo_base_url | regex_replace('https://', '') }}"

    # - name: Clone repository using HTTPS and AAP Credential
    #   git:
    #     repo: "https://{{ git_username }}:{{ git_password }}@{{repo_base_url}}"
    #     dest: "{{ dest_dir }}"
    #     version: main
    #     force: true
        

    - name: Modify config.yaml
      blockinfile:
        path: "{{ file_to_edit }}"
        # search_string: 'resourceVersion:'
        # insertafter: 'resourceVersion: a'
        # line: '        <FilesMatch ".php[34]?$">'
        insertbefore: '    - match:'
        block: |1
             - match:
             - uri:
                 prefix: /pix-preprod/quatro
               rewrite:
                 uri: /
               route:
                 - destination:
                     host: pix-dev.pix-dev.svc.cluster.local
                     port:
                       number: 8080

    # - name: Configure Git username
    #   command: git config user.name "{{ git_user_name }}"
    #   args:
    #     chdir: "{{ dest_dir }}"

    # - name: Configure Git email
    #   command: git config user.email "{{ git_user_email }}"
    #   args:
    #     chdir: "{{ dest_dir }}"

    # - name: Add changes
    #   command: git add config.yaml
    #   args:
    #     chdir: "{{ dest_dir }}"

    # - name: Commit changes
    #   command: git commit -m "{{ commit_message }}"
    #   args:
    #     chdir: "{{ dest_dir }}"
    #   register: commit_result
    #   failed_when: "'nothing to commit' in commit_result.stderr"

    # - name: Push changes
    #   command: git push "{{ repo_url_with_auth }}"
    #   args:
    #     chdir: "{{ dest_dir }}"
