apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{values.topic_name}}
  description: ${{values.description}}
spec:
  type: kafka-topic
  owner: "user1"
  dependencyOf:
    - component:my-quarkus-app
