apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-devbox-template
  title: Create Azure Dev Box
  description: Create a new Azure Dev Box from a template, authenticated as the logged-in user.
spec:
  owner: team-devtools
  type: service

  parameters:
    - title: Azure Dev Box Configuration
      required:
        - devBoxName
        - projectName
        - poolName
        - accessToken
      properties:
        devBoxName:
          title: Dev Box Name
          type: string
          description: Name for the new Dev Box
        projectName:
          title: Project Name
          type: string
          default: 'your-project-name'
          description: Name for the Azure Dev Box project
        poolName:
          title: Pool Name
          type: string
          default: 'three-horizons-pool'
          description: Pool name for the Azure Dev Box project
        accessToken:
          title: AccessToken
          type: string
          description: Pool name for the Azure Dev Box project
          ui:field: ValidateKebabCase
          

  steps:
    - id: create-devbox
      name: Dev Center Create Dev Box
      action: azure:create-devbox
      input:
        devBoxName: ${{ parameters.devBoxName}}
        projectName: ${{ parameters.projectName }}
        poolName: ${{ parameters.poolName }}
        accessToken: ${{ parameters.accessToken }}

  output:
    links:
      - title: 'Go to Azure DevBoxes'
        url: '/azure-devbox'
        icon: dashboard
