apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-devbox-template
  title: Create Azure Dev Box
  description: Create a new Azure Dev Box from a template, authenticated as the logged-in user.
spec:
  owner: team-devtools
  type: service

  parameters:
    - title: Azure Dev Box Configuration
      required:
        - devBoxName
        - projectName
      properties:
        devBoxName:
          title: Dev Box Name
          type: string
          description: Name for the new Dev Box
        projectName:
          title: Project Name
          type: string
          description: Name for the Azure Dev Box project

  steps:
    - id: login
      name: Azure Login (Device Code)
      action: azure:create-devbox
      input:
        devBoxName: ${{ parameters.devBoxName}}
        projectName: ${{ parameters.projectName }}

  # output:
  #   links:
  #     - title: Azure Dev Center
  #       url: ${{ parameters.devCenterUri }}
