- name: Create RHDH Operator Group
  k8s:
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('template', 'rhdh-operatorgroup.yaml.j2') }}"

- name: Create RHDH Subscription
  k8s:
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('template', 'rhdh-subscription.yaml.j2') }}"

- name: Wait for RHDH operator to install
  k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: backstages.rhdh.redhat.com
    namespace: '{{ cluster_project }}'
  register: crd_rhdh
  until: crd_rhdh.resources | list | length == 1
  retries: 10
  delay: 30

- name: Create the RHDO Instance CR
  k8s:
    state: present
    resource_definition:  "{{ lookup('template', 'rhdh-instance.yaml.j2') }}"
