apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: modify-file-and-push
  title: Clone, Replace in File, and Push
  description: Clona um repositório, faz uma substituição de texto em um arquivo e faz push de volta.
spec:
  owner: user:guest
  type: automation

  parameters:
    - title: Repository Info
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository URL
          type: string
          description: Git repository to clone and modify

    - title: File Modification
      required:
        - filePath
        - searchPattern
        - replacement
      properties:
        filePath:
          title: Caminho do Arquivo
          type: string
          description: Caminho relativo do arquivo a ser modificado (ex: config/config.yaml)

        searchPattern:
          title: Padrão de Busca (Regex)
          type: string
          description: Padrão de texto que será substituído (ex: replicas: [0-9]+)

        replacement:
          title: Novo Valor
          type: string
          description: Texto que vai substituir o padrão encontrado

  steps:
    - id: fetch-repo
      name: Fetch Repository
      action: fetch:template
      input:
        url: '{{ parameters.repoUrl }}'
        targetPath: ./workspace

    - id: replace-content
      name: Replace content in file
      action: roadiehq:utils:fs:replace
      input:
        files:
          - ./workspace/{{ parameters.filePath }}
        find: '{{ parameters.searchPattern }}'
        replace: '{{ parameters.replacement }}'

    - id: git-commit
      name: Commit Changes
      action: git:commit
      input:
        workingDirectory: ./workspace
        message: "chore: automated file update via Backstage Template"

    - id: git-push
      name: Push Changes
      action: git:push
      input:
        workingDirectory: ./workspace
