apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: modify-yaml-and-push
  title: Clone, Edit, and Push6
  description: Clones a repository, edits a file, and pushes back to the same repo.
  
spec:
  owner: user:guest
  type: automation
  parameters:
    - title: Repository Info
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository URL
          type: string
          description: Git repository to clone and modify (e.g., github.com?repo=org/repo)

    - title: YAML Modification
      required:
        - yamlPath
        - yamlKey
        - newValue
      properties:
        yamlPath:
          title: Path to YAML file
          type: string
          description: Relative path to the YAML file (e.g., config/config.yaml)

        yamlKey:
          title: YAML Key to Modify
          type: string
          description: The YAML key to change (dot notation supported, e.g., spec.replicas)

        newValue:
          title: New Value
          type: string
          description: New value to set for the YAML key

  steps:
    - id: clone
      name: Clone Repository
      action: fetch:template
      input:
        url: '{{ parameters.repoUrl }}'
        targetPath: ./workspace

    - id: write-file1
      name: Write file
      action: roadiehq:utils:fs:write
      input:
        path: ./workspace/README.md
        content: |
          # Novo README
          
          Este arquivo foi criado automaticamente por um template do Backstage.
          
          - Gerado via Scaffolder 1


    - id: write-file2
      name: Write file
      action: roadiehq:utils:fs:write
      input:
        path: ./workspace/teste/README.md
        content: |
          # Novo README
          
          Este arquivo foi criado automaticamente por um template do Backstage.
          
          - Gerado via Scaffolder 2


    # - id: replace-content
    #   name: Replace content in file
    #   action: roadiehq:utils:fs:replace
    #   input:
    #     files:
    #       - file: ./workspace/teste/config.yaml
    #         find: '{{ parameters.yamlKey }}'
    #         replaceWith: '{{ parameters.newValue }}'
        
    # - id: git-commit
    #   name: Commit Changes
    #   action: git:commit
    #   input:
    #     workingDirectory: ./workspace
    #     message: "chore: automated YAML update via Backstage Template"

    # - id: git-push
    #   name: Push Changes
    #   action: git:push
    #   input:
    #     workingDirectory: ./workspace

    - id: push-to-gitlab
      name: Push to GitLab
      action: gitlab:repo:push
      input:
        repoUrl: '{{ parameters.repoUrl }}'
        sourcePath: ./workspace
        branchName: master
        commitMessage: 'feat: Arquivo gerado automaticamente pelo Backstage Scaffolder'
