apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: strangler-pattern
  title: Strangler Pattern
  description: Strangle a monolith
  
spec:
  owner: user:guest
  type: automation
  parameters:
  - title: Service Parameters
    required:
      - app_service
      - app_namespace
      - uri_prefix
      - uri_rewrite
    properties:
      
      app_namespace:
        title: App Namespace
        type: string
        description: Unique name of the component
        default: servlet
        ui:field: EntityNamePicker
      uri_prefix:
        title: URI Prefix
        type: string
        description: Unique name of the component
        default: service-mesh-demo/serviceA
        ui:field: EntityNamePicker
      app_service:
        title: Service Destination
        type: string
        description: Internal OpenShift Service
        default: offline-dev.offline-dev.svc.cluster.local
        ui:field: EntityNamePicker
      uri_rewrite:
        title: URI Rewrite
        type: string
        description: Unique name of the component
        default: hello
        ui:field: EntityNamePicker
      
  steps:
    - id: launch
      name: Launch
      action: rhaap:launch-job-template
      input:
        token: RfMQBrMqPzw9q42q1vs7ln54uU72w4
        values:
          template:
            id: 10
            name: clone-edit-push
          extraVariables:
            git_repository: ${{ parameters.app_service }}
            git_repository: ${{ parameters.app_namespace }}-gitops
            git_repository: ${{ parameters.uri_prefix }}
            git_repository: ${{ parameters.uri_rewrite }}
            
  output:
    links:
      - title: URL
        url: ${{ steps.launch.output.data.url }}
    text:
      - title: Status
        content: ${{ steps['launch'].output.data.status }}
