kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: {{ .Values.topic.name }}
  labels:
    strimzi.io/cluster: my-cluster
  namespace: my-kafka
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
